name: TEST WF

on:
  workflow_dispatch:

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        LAST_NAME: Octocat
      run: |
        echo $LAST_NAME.
